
services:
  pg_db:
    image: postgres:16.4
    ports:
      - "54320:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./assets/init_back.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data/
    container_name: pg_db
    restart: unless-stopped
    networks:
      - backend

  back1:
    env_file:
      - .env
    build:
      context: .
      dockerfile: backend/cmd/group1/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - pg_db
    networks:
      - backend

volumes:
  pg_data:


networks:
  backend:
    driver: bridge