
services:
  consul:
    image: hashicorp/consul
    ports:
      - "8500:8500"
    networks:
      - backend

  redis_service:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    container_name: redis_service
    restart: unless-stopped
    networks:
      - balancer

  pg_db:
    image: postgres:16.4
    ports:
      - "54320:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data/
    container_name: pg_db
    restart: unless-stopped
    networks:
      - backend


  back1:
    build:
      context: .
      dockerfile: backend/cmd/main/Dockerfile
    ports:
      - "8080:8080"

volumes:
  pg_data:
  redis_data:

networks:
  balancer:
    driver: bridge
  backend:
    driver: bridge