log:
  _default:
    level: info
    file:  app.log
    max_age: 14
    max_size: 20   # МБ
    max_backups: 7
  group:
    level: debug
    file:  group.log
  balancer:
    level: debug
    file:  balancer.log
